---
sudo: required
services: docker
addons:
  apt:
    packages:
    - docker-ce
matrix:
  include:
  - env: ELASTIC_STACK_VERSION=5.x
  - env: ELASTIC_STACK_VERSION=6.x
  fast_finish: true
install: ci/unit/docker-setup.sh
script: ci/unit/docker-run.sh
