import:
- logstash-plugins/.ci:travis/defaults.yml@1.x
- logstash-plugins/.ci:travis/exec.yml@1.x

env:
  jobs:
    - ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk17.env
    - SNAPSHOT=true ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk17.env
