# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('io.netty', 'netty-all', '4.1.65.Final')
require_jar('commons-io', 'commons-io', '2.8.0')
require_jar('org.apache.logging.log4j', 'log4j-core', '2.9.1')
require_jar('org.logstash.inputs', 'logstash-input-tcp', '6.2.2')
